$ErrorActionPreference = "Stop"

$root = Get-Location

$folderRegex = '^terminal-(?<version>\d+(\.\d+){2,3})$'
$archiveRegEx = '^Microsoft\.WindowsTerminal_(?<version>\d+(\.\d+){2,3})_x64\.zip$'

$src = Split-Path $root -Parent
$dest = Join-Path $root "build"

$archive = Get-ChildItem $src -File | Where-Object {
  $_.Name -Match $archiveRegEx
} | Sort-Object -Property {
  if ($_.Name -match $archiveRegEx) { [Version]$Matches.version}
} | Select-Object -First 1

$work = Join-Path $dest "tmp"
New-Item $work -ItemType Directory -Force | Out-Null
Expand-Archive -DestinationPath $work -LiteralPath $archive.FullName -Force

$item = Get-ChildItem $work -Directory | Where-Object {
  $_.Name -match $folderRegex
}

if (-not $item) {
  throw "${archive}: distribution folder not found"
}

$releaseFolder = Join-Path $dest $item.Name
if (Test-Path $releaseFolder) { Remove-Item $releaseFolder -Recurse -Force }
Move-Item -LiteralPath $item.FullName -Destination $dest -Force
if (!(Test-Path "$work\*")) { Remove-Item $work }

$item.Name -match $folderRegex | Out-Null
$version = $Matches.version

$filename = "wt-version.inc.iss"
Write-Host "Creating '$filename' for $version"
@(
  "// autogenerated"
  "#define TerminalFolder `"${releaseFolder}`""
  "#define TerminalVersion `"${version}`""
) -join "`n" | Set-Content -Path $filename -Encoding UTF8 -Force
